on:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Replace Firebase API Key
        run: |
          sed -i 's/__FIREBASE_API_KEY__/${{ secrets.APIKEY }}/g' index.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  
          branch: main
